FORMAT: 1A
HOST: http://localhost:3000

# VUTTR

Very Useful Tools to Remember (VUTTR). API desenvolvida como desafio proposto para a BossaBox.

# Group API

## About [/]

Aqui está um breve status da api, como nome e versão atual.

# Group Ferramentas

## Ferramentas [/tools]

### Criar ferramenta [POST]

+ Request Criar uma ferramenta

    + Headers
    
            Authorization: Bearer JWT
            Accept: application/json
            Content-Type: application/json
    + Attributes (ToolPost)
        

+ Response 201 (application/json)
    + Attributes
        + title (string)
        + link (string)
        + description (string)
        + tags (array)
        + id (string)
        + __v (number)

+  Response 500 (application/json)
    + Attributes
        + message (string)
        + error (string)

### Listar ferramentas [GET]

+ Response 200 (application/json)
    + Attributes (array[Tool])

+ Response 404 (application/json)
    + Attributes (Error)

## Ferramentas [/tools?tag={tag}]

### Buscar por tag [GET]

+ Parameters
    + tag: teste (string, required) - Tag a ser pesquisada

+ Response 200 (application/json)
    + Attributes (array[Tool])


## Ferramenta [/tools/{id_tool}]

+ Parameters
    + id_tool: 5cdf26cd88952753d4654b12 (string, required) - Identificador da ferramenta    

### Ver uma ferramenta [GET]

+ Response 200 (application/json)
    + Attributes (Tool)

### Editar uma ferramenta [PUT]

+ Request Atualizar uma ferramenta

    + Headers
    
            Authorization: Bearer JWT
            Accept: application/json
            Content-Type: application/json
    + Attributes (ToolUpdate)

+ Response 200 (application/json)
    + Attributes (Tool)

### Excluir ferramenta [DELETE]

    + Headers
    
            Authorization: Bearer JWT

+ Response 200 (application/json)
    + Attributes
        + message: Tool removed! (string)

# Data Structures

## ToolPost (object)
+ title: Minha Ferramenta (string, required) - Título da ferramenta
+ link: http://minhaferramenta.com.br (string, required) - Link de acesso a ferramenta
+ description: Descricão da minha ferramenta (string, required) - Descricão da ferramenta
+ tags: minha, ferramenta, node (array) - Lista de tags da ferramenta

## ToolUpdate (object)
+ title: Minha Ferramenta (string) - Título da ferramenta
+ link: http://minhaferramenta.com.br (string) - Link de acesso a ferramenta
+ description: Descricão da minha ferramenta (string) - Descricão da ferramenta
+ tags: minha, ferramenta, node (array) - Lista de tags da ferramenta

## Tool (object)
+ id: 5ced3c63c5eba42d7c878a6e (string) - Id da ferramenta 
+ title: Minha Ferramenta (string) - Título da ferramenta
+ link: http://minhaferramenta.com.br (string) - Link de acesso a ferramenta
+ description: Descricão da minha ferramenta (string) - Descricão da ferramenta
+ tags: minha, ferramenta, node (array) - Lista de tags da ferramenta

## Id (object)
+ id (string) - Id a ser processado

## Error (object)
+ code: 400 (number) - Status code
+ message (string) - Mensagem do status
+ description (string) - Descrição do status